# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'posts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for posts
  pod 'Alamofire'
  pod 'Material', '3.1.8'
  pod 'RealmSwift'

  target 'postsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'postsUITests' do
    # Pods for testing
  end

end
